In [1]:
import torch

In [2]:
x = torch.empty(5, 3)

uninitialized

In [3]:
x

tensor([[ 0.0000e+00,  2.5244e-29,  0.0000e+00],
        [ 2.5244e-29,  2.4923e+37,  4.5848e-41],
        [ 0.0000e+00,  7.0065e-45,  2.5039e+37],
        [ 4.5848e-41,  0.0000e+00,  9.1843e-41],
        [-2.1974e+24,  2.0005e+00, -2.2429e+24]])

In [10]:
x.size()

torch.Size([5, 3])

In [11]:
x.shape

torch.Size([5, 3])

In [4]:
torch.empty(5, 3)

tensor([[0.0000e+00, 2.5244e-29, 0.0000e+00],
        [2.5244e-29, 1.2612e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])

random

In [5]:
torch.rand(5, 3)

tensor([[0.0020, 0.6495, 0.5403],
        [0.5422, 0.2457, 0.1604],
        [0.9450, 0.0615, 0.5813],
        [0.9635, 0.9486, 0.6933],
        [0.6517, 0.5651, 0.2026]])

In [6]:
torch.rand(5, 3)

tensor([[0.9434, 0.0492, 0.3680],
        [0.4706, 0.7111, 0.0533],
        [0.2179, 0.8441, 0.1567],
        [0.0508, 0.4749, 0.6712],
        [0.9972, 0.5376, 0.0800]])

dtype long & 0 values

In [7]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
torch.zeros?

Docstring:
zeros(*sizes, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

Returns a tensor filled with the scalar value `0`, with the shape defined
by the variable argument :attr:`sizes`.

Args:
    sizes (int...): a sequence of integers defining the shape of the output tensor.
        Can be a variable number of arguments or a collection like a list or tuple.
    out (Tensor, optional): the output tensor
    dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
        Default: if ``None``, uses a global default (see :func:`torch.set_default_tensor_type`).
    layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
        Default: ``torch.strided``.
    device (:class:`torch.device`, optional): the desired device of returned tensor.
        Default: if ``None``, uses the current device for the default tensor type
        (see :func:`torch.set_default_tensor_type`). :attr:`device` will be the 

In [9]:
torch?

Type:        module
String form: <module 'torch' from '/Users/wararaki/.pyenv/versions/3.6.3/lib/python3.6/site-packages/torch/__init__.py'>
File:        ~/.pyenv/versions/3.6.3/lib/python3.6/site-packages/torch/__init__.py
Docstring:  
The torch package contains data structures for multi-dimensional
tensors and mathematical operations over these are defined.
Additionally, it provides many utilities for efficient serializing of
Tensors and arbitrary types, and other useful utilities.

It has a CUDA counterpart, that enables you to run your tensor computations
on an NVIDIA GPU with compute capability >= 3.0.


calc

In [12]:
x = torch.rand(5, 3)
y = torch.rand(5, 3)

In [13]:
x

tensor([[0.7461, 0.5556, 0.8755],
        [0.6854, 0.7137, 0.9227],
        [0.8236, 0.0798, 0.8228],
        [0.8479, 0.5644, 0.7457],
        [0.8234, 0.1777, 0.7496]])

In [14]:
y

tensor([[0.6530, 0.2818, 0.6490],
        [0.8311, 0.8909, 0.8371],
        [0.7302, 0.1904, 0.9798],
        [0.0904, 0.6513, 0.2102],
        [0.8226, 0.4479, 0.3194]])

In [15]:
torch.add(x, y)

tensor([[1.3991, 0.8373, 1.5245],
        [1.5165, 1.6046, 1.7598],
        [1.5538, 0.2701, 1.8026],
        [0.9383, 1.2156, 0.9559],
        [1.6459, 0.6256, 1.0690]])

resize

In [16]:
y.view(15)

tensor([0.6530, 0.2818, 0.6490, 0.8311, 0.8909, 0.8371, 0.7302, 0.1904, 0.9798,
        0.0904, 0.6513, 0.2102, 0.8226, 0.4479, 0.3194])